CrudNet8MVC/Models/Contacto.cs
using System.ComponentModel.DataAnnotations;

namespace CrudNet8MVC.Models
{
    public class Contacto
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El teléfono es obligatorio")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "El celular es obligatorio")]
        public string Celular { get; set; }

        [Required(ErrorMessage = "El email es obligatorio")]
        public string Email { get; set; }

        public DateTime FechaCreacion { get; set; }
    }
}

CrudNet8MVC/Models/ErrorViewModel.cs
namespace CrudNet8MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNet8MVC/Controllers/InicioController.cs
using CrudNet8MVC.Datos;
using CrudNet8MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CrudNet8MVC.Controllers
{
    public class InicioController : Controller
    {
       private readonly ApplicationDbContext _contexto;

        public InicioController(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _contexto.Contacto.ToListAsync());
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Contacto contacto)
        {
            if (ModelState.IsValid)
            {

                //Agregar la fecha y hora actual
                contacto.FechaCreacion = DateTime.Now;

                _contexto.Contacto.Add(contacto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }


        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contacto.Find(id);
            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Contacto contacto)
        {
            if (ModelState.IsValid)
            {               
                _contexto.Update(contacto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contacto.Find(id);
            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpGet]
        public IActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contacto.Find(id);
            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarContacto(int? id)
        {
            var contacto = await _contexto.Contacto.FindAsync(id);
            if(contacto == null)
            {
                return View();
            }

            //Borrado
            _contexto.Contacto.Remove(contacto);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));            
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNet8MVC/Views/Inicio/Borrar.cshtml
@model CrudNet8MVC.Models.Contacto
@{
    ViewData["Title"] = "Borrar Contacto";
}

<h1 class="text-center">Contacto con .NET 8 (.NET Core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Borrar Usuario</strong></h3>
            </div>
            <div class="card-body">

                <form asp-action="Borrar">

                    <!--ID del usuario como campo oculto *-->
                    <input type="hidden" asp-for="Id" />

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" readonly />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" readonly />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" readonly />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" readonly />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-success d-block mx-auto"><i class="fa fa-user" aria-hidden="true"></i> Borrar Usuario</button>
                    </div>
                </form>

                <a asp-controller="Inicio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Crear.cshtml
@model CrudNet8MVC.Models.Contacto
@{
    ViewData["Title"] = "Crear Nuevo Contacto";
}

<h1 class="text-center">Contacto con .NET 8 (.NET Core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Crear Usuario</strong></h3>
            </div>
            <div class="card-body">
               
                <form asp-action="Crear" method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el teléfono" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-secondary d-block mx-auto"><i class="fa fa-user" aria-hidden="true"></i> Crear Usuario</button>
                    </div>
                </form>

                <a asp-controller="Inicio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Detalle.cshtml
@model CrudNet8MVC.Models.Contacto
@{
    ViewData["Title"] = "Detalle Contacto";
}

<h1 class="text-center">Contacto con .NET 8 (.NET Core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Editar Usuario</strong></h3>
            </div>
            <div class="card-body">

                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre: </strong>@Html.DisplayFor(m => m.Nombre)</li>
                    <li class="list-group-item"><strong>Teléfono: </strong>@Html.DisplayFor(m => m.Telefono)</li>
                    <li class="list-group-item"><strong>Celular: </strong>@Html.DisplayFor(m => m.Celular)</li>
                    <li class="list-group-item"><strong>Email: </strong>@Html.DisplayFor(m => m.Email)</li>
                    <li class="list-group-item"><strong>Fecha: </strong>@Html.DisplayFor(m => m.FechaCreacion)</li>
                </ul>
               

                <a asp-controller="Inicio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Editar.cshtml
@model CrudNet8MVC.Models.Contacto
@{
    ViewData["Title"] = "Editar Contacto";
}

<h1 class="text-center">Contacto con .NET 8 (.NET Core MVC)</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Editar Usuario</strong></h3>
            </div>
            <div class="card-body">

                <form asp-action="Editar">

                   <!--ID del usuario como campo oculto *-->
                   <input type="hidden" asp-for="Id" />

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el teléfono" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingresa el celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-primary d-block mx-auto"><i class="fa fa-user" aria-hidden="true"></i> Editar Usuario</button>
                    </div>
                </form>

                <a asp-controller="Inicio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Index.cshtml
@model IEnumerable<CrudNet8MVC.Models.Contacto>
@{
    ViewData["Title"] = "Lista de Contactos";
}

<h1 class="text-center">Contacto con .NET 8 (.NET Core MVC)</h1>
<div class="row">
    <div class="offset-9 col-3 mb-3">
        <a asp-action="Crear" asp-controller="Inicio" class="btn btn-secondary d-block mx-auto btn-lg">
            <i class="fa fa-plus" aria-hidden="true"></i> Nuevo Usuario
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Usuarios</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if(Model.Count() > 0)
                    {
                        <table class="table table-bordered" id="tblUsuarios" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(m => m.Id)</th>
                                    <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                    <th>@Html.DisplayNameFor(m => m.Telefono)</th>
                                    <th>@Html.DisplayNameFor(m => m.Celular)</th>
                                    <th>@Html.DisplayNameFor(m => m.Email)</th>
                                    <th>@Html.DisplayNameFor(m => m.FechaCreacion)</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var item in Model){
                                    <tr>
                                        <td>@Html.DisplayFor(m => item.Id)</td>
                                        <td>@Html.DisplayFor(m => item.Nombre)</td>
                                        <td>@Html.DisplayFor(m => item.Telefono)</td>
                                        <td>@Html.DisplayFor(m => item.Celular)</td>
                                        <td>@Html.DisplayFor(m => item.Email)</td>
                                        <td>@Html.DisplayFor(m => item.FechaCreacion)</td>
                                        <td>
                                            <a class="btn btn-warning" asp-action="Editar" asp-route-id="@item.Id"><i class="fa fa-pencil" aria-hidden="true"></i> Editar</a>
                                            <a class="btn btn-secondary" asp-action="Detalle" asp-route-id="@item.Id"><i class="fa fa-info-circle" aria-hidden="true"></i> Detalle</a>
                                            <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@item.Id"><i class="fa fa-eraser" aria-hidden="true"></i> Borrar</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>No hay registros</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNet8MVC</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudNet8MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudNet8MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudNet8MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>